### ISSUE TITLE
Hide error output

### ISSUE THREAD

**Issue by mtorpey** [mtorpey/PackageManager#13]
The tests pass fine, but they also spew loads of stderr output to the screen.  I don't see a way to avoid this, since `Process` doesn't appear to have an option to redirect error output.  Is there a way to tidy this up?  Perhaps @fingolfin knows?

**Comment by ChrisJefferson** [comment]
Catching standard error isn't possible at the moment. I'm tempted to just merge it into the existing "output", it would be easy (but a bunch of code) to add an optional argument to Process which would allow catching errout.

**Comment by mtorpey** [comment]
I've managed to do this for now with a workaround (calling `sh -c <command> 2>&1` instead of just `<command>`).  If `Process` gets modified we'll be able to just use the argument instead.
