### ISSUE TITLE
Perhaps rename InstallPackageFromName to InstallPackageByName ?

### ISSUE THREAD

**Issue by fingolfin** [mtorpey/PackageManager#19]

**Comment by mtorpey** [comment]
`InstallPackageByName` is better English, but on the other hand `InstallPackageFromName` is consistent with all the other methods.  I'm happy to change if you think it's a good idea, but the question mark on the issue title makes me wonder whether that's definitely your opinion.  What d'you think? :)

**Comment by mtorpey** [comment]
I don't think either of us care too much about this, so I've left it for now.  Willing to reconsider later if anyone cares!
