### ISSUE TITLE
Optionally allow using package without curlInterface?

### ISSUE THREAD

**Issue by fingolfin** [mtorpey/PackageManager#2]
Installing `curlInterface` requires an external dependency (`libcurl`) and thus is a hurdle to users by itself.

Perhaps `curlInterface` could be moved to `SuggestedOtherPackages`; then, if it is not present, try to invoke `wget` and/or `curl` via `Exec` or `Process` as a fallback.

**Comment by mtorpey** [comment]
Done in 5dec23e.  Both `wget` and `curl` are tried (and that's flexible).

**Comment by dimpase** [comment]
I don't see curl tried at all if I try it from macOS + homebrew. If I install homebrew's wget, I end up with weird
```
gap> InstallPackage("jupyterviz");
#I  Getting PackageInfo URLs...
#I  Retrieving PackageInfo.g from https://nathancarter.github.io/jupyterviz/PackageInfo.g ...
#I  Downloading archive from URL https://github.com/nathancarter/jupyterviz/releases/download/v1.5.1/jupyterviz-1.5.1.tar.gz ...
#I  Saved archive to /var/folders/lh/tzyg2vbn4z99vg__rg2_t_f80000gs/T//tmsZRsQZ/jupyterviz-1.5.1.tar.gz.pkgman
#I  Archive should contain 1 directory (not 5)
false
```
Why is that `.pkgman` suffix there?! As far as I and `file` can see, `jupyterviz-1.5.1.tar.gz.pkgman` is a `.tgz` file.

**Comment by dimpase** [comment]
Oh, OK, it's `jupyterviz` tar file that extracts in `./` rather than `jupyterviz-1.5.1`. That's why `5`.

**Comment by dimpase** [comment]
But I don't know why this happens. The tarfile is OK in this sense.

**Comment by fingolfin** [comment]
The problem is caused by some files in that archive containing spaces, and the code in PackageManager not dealing with those property. I'll open a new issue.
