### ISSUE TITLE
Add `InstallPackage(what)` with urls, package names, or lists thereof?

### ISSUE THREAD

**Issue by fingolfin** [mtorpey/PackageManager#3]
It would be nice if I one could do all of the following:
1. [x] `InstallPackage("https://.../pkg.tar.gz");` to download and install a package tarball (possibly verify later on that this creates a valid pkg dir, with a `PackageInfo.g` in it?)
2. [x] `InstallPackage("https://.../PackageInfo.g");` to install the package in that `PackageInfo.g` (essentially, extract the download URL from there and go to step 1)
3. [x] `InstallPackage("https://.../pkg.git");` -> clone the package repository by invoking `git
4. [x] the same for `.hg` / Mercurial -- a few packages are in hg repos on BitBucket
5. [x] Perhaps don't restrict to https, but also support e.g. ftp, ftps? (Not sure whether that's actually useful these days, though)

**Comment by fingolfin** [comment]
In addition, one could even allow passing in multiple arguments, or a list, to install multiple packages at once

**Comment by mtorpey** [comment]
I'll be ticking these off one by one!

**Comment by mtorpey** [comment]
First three are done.  I'll be leaving the others for now, while I work on a unifying `InstallPackage` function that chooses the correct one, and make the whole thing a bit more reliable and stable.

**Comment by fingolfin** [comment]
Great, thanks!

**Comment by mtorpey** [comment]
The last two points here should be easy.  If they are, they should go in the `0.1` release.  Otherwise, they could be added later.

**Comment by mtorpey** [comment]
Now we have Mercurial support, the only thing left is FTP.  This might already be working by accident – I'll test it tomorrow.

**Comment by fingolfin** [comment]
Curl supports ftp, wget propably too

**Comment by mtorpey** [comment]
Skipping ftp (but it probably works anyway!)
