### ISSUE TITLE
Add support for compiling packages

### ISSUE THREAD

**Issue by fingolfin** [mtorpey/PackageManager#5]
It would be cool if packages were also compiled. This could work like that: after extracting the package, invoke `GAPROOT/bin/BuildPackages.sh --strict --with-gaproot=GAPROOT dir-of-installed-pkg`

Actually, you have to invoke it using a shell. It might look something like this (untested):
```gap
    shell := Filename( DirectoriesSystemPrograms(), "sh" );
    if fullcmd = fail then
        return fail; # indicate to caller that we could not locate the program
    fi;

    dir := DirInWhichPackagesAreInstalled();
    instream := InputTextUser();
    outstream := OutputTextUser();
    result := Process( dir, shell, instream, outstream, [ "-c",
        Concatenation( GAPROOT, "/bin/BuildPackages.sh --strict --with-gaproot=", GAPROOT, " ", name_of_new_package_dir ) ] );
```

Of course one could add some nice messags before and after ("starting to build packages")

**Comment by mtorpey** [comment]
Done, and all tested!  This uses `bin/BuildPackages.sh`, so it's only as reliable as that.  But it works on all the packages I've tried.
