### ISSUE TITLE
Start a test suite

### ISSUE THREAD

**Issue by fingolfin** [mtorpey/PackageManager#6]
I'd recommend that a test suite be created (and then Travis & Codecov tests set up for it). Don't put it off too long...

To do this w/o disturbing the user, I'd make the package installation path configurable (it doesn't have to be a user configuration; e.g. you could just add a check to `PKGMAG_CustomPackageDir`, which checks if a global `PKGMAN_CustomPackageDir` is bound, and if so, return it.

Then, for the tests, point `PKGMAN_CustomPackageDir` at a temp dir, and try to install packages in various ways.

**Comment by mtorpey** [comment]
Done, much as @fingolfin suggested.
